parameters:
#    sm_sitio.example.class: SM\Bundle\SitioBundle\Example

services:
#    sm_sitio.example:
#        class: %sm_sitio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
