sm_admin_portada:
    resource: @SMAdminBundle/Resources/config/routing/portada.yml
    prefix: /

sm_admin_cliente:
    resource: @SMAdminBundle/Resources/config/routing/cliente.yml
    prefix:   /cliente

sm_admin_empleado:
    resource: @SMAdminBundle/Resources/config/routing/empleado.yml
    prefix:   /empleado

sm_admin_departamento:
    resource: @SMAdminBundle/Resources/config/routing/departamento.yml
    prefix:   /departamento

sm_admin_ciudad:
    resource: @SMAdminBundle/Resources/config/routing/ciudad.yml
    prefix:   /ciudad

sm_admin_producto:
    resource: @SMAdminBundle/Resources/config/routing/producto.yml
    prefix:   /producto

sm_admin_clase_producto:
    resource: @SMAdminBundle/Resources/config/routing/clase_producto.yml
    prefix:   /claseproducto

sm_admin_factura:
    resource: @SMAdminBundle/Resources/config/routing/factura.yml
    prefix:   /factura

sm_admin_tipo_incidente:
    resource: @SMAdminBundle/Resources/config/routing/tipo_incidente.yml
    prefix:   /tipoincidente