parameters:
#    sm_admin.example.class: SM\Bundle\AdminBundle\Example

services:
#    sm_admin.example:
#        class: %sm_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
