sm_admin_factura:
    pattern: /
    defaults: {_controller: SMAdminBundle:Factura:index }

sm_admin_factura_buscar_producto:
    pattern: /buscar-producto
    defaults: {_controller: SMAdminBundle:Factura:buscarProducto }