parameters:
#    sm_market.example.class: SM\Bundle\MarketBundle\Example

services:
#    sm_market.example:
#        class: %sm_market.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
